# Generated by Django 3.2.3 on 2021-05-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
