# Generated by Django 3.2.3 on 2021-05-25 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0006_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('year_of_graduation', models.IntegerField()),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.certificate_type')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.department')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.school')),
            ],
        ),
    ]
